apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EUXhOREE1TkRVME5sb1hEVE16TURReE1UQTVOVEEwTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTndoCnFPUFdGZTVlWGtiZ2xVQzlUZndOeWVDVXhXbmFLblBZeXJrYkZRMTIveUtOQ2taVERWZWhCT2h2YXVRU3BTa1oKTVpFZ3ZlU2w5b2k0alhYL2hqR0R5T21oSXYrVWcxd01IUWVncm1QNGZ0clZvZFgvZ1NpeEpLcDduN0MzTXhnKwpQY3ZPUkxYbGJPTkdZcWRpaHZwa0VhQmFiZGNNUHVqbDdLUTZ2UE9qSGM1eG1xUHh2SkdQYnBTQWhHUG1MOTdWClo1NGp3S0s4UDRtL3BZaEhKbEJlSDl2dGdXS1VNYTVCRk9aMWFyUVUwMHp4a3E3NUgxMjBET0U0MnBScDV4ZWwKQzkzSHFjeFBuVUdmeGdqVWY1alQrcDkrcTZYTmN3TkluZGJLMUFPZVJoYjkvVFpDd2FhSFFJRVhYdm93UUk4VwpYak9UQ3RMWnh0RFFySUdPMG04Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSTlXaGdtNlMwb2NIR2pxOWNFdDlHR1p6Mm1nTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmNRei81R2FucmVEQ1dPbmIvY2FyRVZpQTRodUprdVA5RkZzenpIRU4zSmV3OAo2MklzWTdVNVpnYVd0M3h6elJFVjFhZFNTd09pVUI4cGVtMUhlUk9OVGk1OFFVa0tNK1dLZlhXNXMySDRFeUJJCmxFdHJNWkYxNTdQRUg1MHdWVFg4cmhVdGx2c0pIMXBNaDRzQlV3YmR1QWlkNDhEQncxL1c1NE12YWN2elNwUmYKNzhLUkQ2R244ZGZWbG9sOVVld0Y1bnhsOUM0aGdjcVE2T1pNMzVRR2F4Q1ErVTV0bklxYk9QQUN3VDJpOWZJVApFdHpJaDhZL2xBcGNReEtRTExMWGNsa0xjdnk3aHYvOUY4clR5S3hITi9BRWZLaHkrM2F2SGt6eis4VFk0R28zCm5NU1BpSlVvT0YwRGw0aE5aVldJMVRRVlkxVWl6djQ3bFlDOGdPUzMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://61.109.215.247:6443
  name: minwon-dev-cluster
contexts:
- context:
    cluster: minwon-dev-cluster
    user: minwon-dev-cluster-admin
  name: minwon-dev-cluster-admin@minwon-dev-cluster
current-context: minwon-dev-cluster-admin@minwon-dev-cluster
kind: Config
preferences: {}
users:
- name: minwon-dev-cluster-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoicloud-kr-gov.com/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "01b4d9d7400f4f20b7f663854a7b06e4"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "plbixSZjBXZCr-eSjJ4PDysRItejFpXHRBZiCueSlRUegOjTQs7wXU7cUjBOh_mGrSnGwJRDSRu3z2T_fJ1mCQ"
      - name: "OS_REGION_NAME"
        value: "kr-gov-central-1"
